### ISSUE TITLE
Registering `DotDiagnosticTracer` in Autofac 8 causes MissingMethodException on any resolve

### ISSUE THREAD

**Issue by DoctorVanGogh** [autofac/Autofac.Diagnostics.DotGraph#14]
## Describe the Bug
Seems the dot diagnostic tracer is incompatible with AF8.

## Steps to Reproduce

- Make a new C# project,
-  Add `Autofac` `8.0.0` 
- Add `Autofac.Diagnostics.DotGraph` `1.0.0`

```c#
using Autofac;
using Autofac.Diagnostics.DotGraph;

internal class Program {

    public class Foo {

    }

    private static void Main(string[] args) {

        var cb = new ContainerBuilder();

        cb.RegisterType<Foo>()
            .AsSelf()
            .SingleInstance();

        var scope = cb.Build();

        var tracer = new DotDiagnosticTracer();

        scope.SubscribeToDiagnostics(tracer);

        var foo = scope.Resolve<Foo>();   // <--- exception here

        Console.WriteLine("Hello, World!");
    }
}
```

## Expected Behavior

No exceptions :wink:

## Exception with Stack Trace

```text
Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=An exception was thrown while executing a resolve operation. See the InnerException for details.
  Source=Autofac
  StackTrace:
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Container.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Program.Main(String[] args) in ....\Program.cs:line 24

  This exception was originally thrown at this call stack:
    Autofac.Diagnostics.DiagnosticTracerBase.Write(string, object)
    Autofac.Diagnostics.DiagnosticTracerBase.System.IObserver<System.Collections.Generic.KeyValuePair<string, object>>.OnNext(System.Collections.Generic.KeyValuePair<string, object>)
    System.Diagnostics.DiagnosticListener.Write(string, object)
    Autofac.Diagnostics.DiagnosticSourceExtensions.OperationStart(System.Diagnostics.DiagnosticListener, Autofac.Core.Resolving.IResolveOperation, Autofac.ResolveRequest)
    Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(Autofac.ResolveRequest)

Inner Exception 1:
MissingMethodException: Method not found: 'Autofac.ResolveRequest Autofac.Core.Resolving.IResolveOperation.get_InitiatingRequest()'.

```

## Dependency Versions

Autofac: 8.0.0
Autofac.Diagnostics.DotGraph:  1.0.0

## Additional Info
Things worked fine using AF 7.1. Also the dot diagnostics package does not have an upper version limit on its AF dependency, so did not expect things to blow with AF8.

**Comment by tillig** [comment]
We generally don't put upper limits on our extension libraries because _most_ of the time that just creates work having to go through every library and release on every core Autofac release or similar.

PR #15 should take care of this.

**Comment by tillig** [comment]
v2.0.0 is released with this fix.
